[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules", "lib","lib/openzeppelin-contracts"]
solc_version = "0.8.26"
post_build = "node scripts/extractAbi.js"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
